name: ActiveJoe.net
favicon: null
layout_spectrum: 0.55261
typography_spectrum: 0.3236457675229758
title: 'Time to get ACTIVE!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c261ca'
    - '#7b357b'
    - '#491b49'
    - '#f7c9f7'
    - '#f9eff8'
  brandStrength: 0.5625
  lightness: 0.8287912823725492
  saturation: 0.5618699551559985
  rhythmicContrast: 0.08298470173031092
purpose: []
